### ISSUE TITLE
通过URDF模型的正逆运动学坐标和实际世界的机械臂的坐标不一致

### ISSUE THREAD

**Issue by milchstrasse565** [waveshareteam/roarm_ws_em0#1]
通过URDF模型的正逆运动学坐标和实际的机械臂的坐标（ESP32串口发过来的世界坐标）不一致，求尽快解决，需要批量购买

**Comment by DUDULRX** [comment]
现在新增了一个hand_tcp虚拟link，使得urdf建模同下位机基本一致，但由于舵机自身执行时会存在虚位，坐标无法达到完全一致
![企业微信截图_17231954332374](https://github.com/user-attachments/assets/05aa346f-658f-4e46-99e6-c44d482ad455)
![企业微信截图_1723442239886](https://github.com/user-attachments/assets/0efae111-fe41-4e75-a8fe-5c928b7b6432)
