### ISSUE TITLE
moveit poses

### ISSUE THREAD

**Issue by giwrgakhhs** [waveshareteam/roarm_ws_em0#4]
how can i add pose on moveit 2 for roarm m2 s

**Comment by DUDULRX** [comment]
steps:
optionally, find the joint angle corresponding to the pose,
select the desired pose joint angle, and record it
```
ros2 launch roarm_description display.launch.py
```
modify the following file "~/roarm_ws_em0/src/roarm_main/roarm_moveit/config/roarm_description.srdf", add pose after line 26,for example, 
```
<group_state name="pose1" group="hand">
    <joint name="base_link_to_link1" value="0"/>
    <joint name="link1_to_link2" value="0.801"/>
    <joint name="link2_to_link3" value="2.401"/>
</group_state>
```
![企业微信截图_17323273607592](https://github.com/user-attachments/assets/def66e7d-00a9-4a3a-912b-9f92542ae06a)

then go to workspaces， recompile 
```
cd ~/roarm_ws_em0/
colcon build --symlink-install --packages-select roarm_moveit 
```
run
```
ros2 launch roarm_moveit interact.launch.py
 ```
click "Goal State" to see the newly added pose
![企业微信截图_17323290846469](https://github.com/user-attachments/assets/d082865f-221b-4bb0-97be-e4b22bd78223)
