### ISSUE TITLE
Feature request: control the LED from ROS

### ISSUE THREAD

**Issue by pondersome** [waveshareteam/roarm_ws_em0#6]
Feature request: control the LED from ROS

**Comment by DUDULRX** [comment]
Sorry, I was busy with other things yesterday and didn't reply in time.
I updated the file,you can replace “roarm_driver.py” .
![image](https://github.com/user-attachments/assets/c5f938a6-0921-4c33-83c6-b58cbdd13bb0)
Then,you can control the LED on the gripper of the robot arm through the following command,data is an integer, the range is [0-255].
`
ros2 topic pub /led_ctrl std_msgs/msg/Float32 {"data: 0"} -1
`

**Comment by pondersome** [comment]
Thank you, this is very helpful. Using it already.
